import type { IDBPDatabase } from "idb";
import type { BirdOrder, BirdFamily, BirdGenus, BirdSpecies } from "@/types";

const SEEDED_KEY = "birding_db_seeded_v1";

export function isSeeded(): boolean {
  return localStorage.getItem(SEEDED_KEY) === "1";
}

export function setSeeded(): void {
  localStorage.setItem(SEEDED_KEY, "1");
}

type BirdingDB = any;

const orders: BirdOrder[] = [
  { id: "passeriformes", name_cn: "雀形目", name_latin: "Passeriformes" },
  { id: "piciformes", name_cn: "鴷形目", name_latin: "Piciformes" },
  { id: "apodiformes", name_cn: "雨燕目", name_latin: "Apodiformes" },
  { id: "coraciiformes", name_cn: "佛法僧目", name_latin: "Coraciiformes" },
  { id: "cuculiformes", name_cn: "鹃形目", name_latin: "Cuculiformes" },
  { id: "strigiformes", name_cn: "鸮形目", name_latin: "Strigiformes" },
  { id: "accipitriformes", name_cn: "鹰形目", name_latin: "Accipitriformes" },
  { id: "falconiformes", name_cn: "隼形目", name_latin: "Falconiformes" },
  { id: "charadriiformes", name_cn: "鸻形目", name_latin: "Charadriiformes" },
  { id: "gruiformes", name_cn: "鹤形目", name_latin: "Gruiformes" },
  { id: "anseriformes", name_cn: "雁形目", name_latin: "Anseriformes" },
  { id: "galliformes", name_cn: "鸡形目", name_latin: "Galliformes" },
  { id: "columbiformes", name_cn: "鸽形目", name_latin: "Columbiformes" },
];

const families: BirdFamily[] = [
  { id: "passeridae", order_id: "passeriformes", name_cn: "雀科", name_latin: "Passeridae" },
  { id: "fringillidae", order_id: "passeriformes", name_cn: "燕雀科", name_latin: "Fringillidae" },
  { id: "paridae", order_id: "passeriformes", name_cn: "山雀科", name_latin: "Paridae" },
  { id: "corvidae", order_id: "passeriformes", name_cn: "鸦科", name_latin: "Corvidae" },
  { id: "turdidae", order_id: "passeriformes", name_cn: "鸫科", name_latin: "Turdidae" },
  { id: "muscicapidae", order_id: "passeriformes", name_cn: "鹟科", name_latin: "Muscicapidae" },
  { id: "sylviidae", order_id: "passeriformes", name_cn: "莺科", name_latin: "Sylviidae" },
  { id: "phylloscopidae", order_id: "passeriformes", name_cn: "柳莺科", name_latin: "Phylloscopidae" },
  { id: "timaliidae", order_id: "passeriformes", name_cn: "画眉科", name_latin: "Timaliidae" },
  { id: "pycnonotidae", order_id: "passeriformes", name_cn: "鹎科", name_latin: "Pycnonotidae" },
  { id: "picidae", order_id: "piciformes", name_cn: "啄木鸟科", name_latin: "Picidae" },
  { id: "apodidae", order_id: "apodiformes", name_cn: "雨燕科", name_latin: "Apodidae" },
  { id: "alcedinidae", order_id: "coraciiformes", name_cn: "翠鸟科", name_latin: "Alcedinidae" },
  { id: "cuculidae", order_id: "cuculiformes", name_cn: "杜鹃科", name_latin: "Cuculidae" },
  { id: "strigidae", order_id: "strigiformes", name_cn: "鸱鸮科", name_latin: "Strigidae" },
  { id: "accipitridae", order_id: "accipitriformes", name_cn: "鹰科", name_latin: "Accipitridae" },
  { id: "falconidae", order_id: "falconiformes", name_cn: "隼科", name_latin: "Falconidae" },
  { id: "laridae", order_id: "charadriiformes", name_cn: "鸥科", name_latin: "Laridae" },
  { id: "charadriidae", order_id: "charadriiformes", name_cn: "鸻科", name_latin: "Charadriidae" },
  { id: "scolopacidae", order_id: "charadriiformes", name_cn: "鹬科", name_latin: "Scolopacidae" },
  { id: "gruidae", order_id: "gruiformes", name_cn: "鹤科", name_latin: "Gruidae" },
  { id: "rallidae", order_id: "gruiformes", name_cn: "秧鸡科", name_latin: "Rallidae" },
  { id: "anatidae", order_id: "anseriformes", name_cn: "鸭科", name_latin: "Anatidae" },
  { id: "phasianidae", order_id: "galliformes", name_cn: "雉科", name_latin: "Phasianidae" },
  { id: "columbidae", order_id: "columbiformes", name_cn: "鸠鸽科", name_latin: "Columbidae" },
];

const genera: BirdGenus[] = [
  { id: "passer", family_id: "passeridae", name_cn: "麻雀属", name_latin: "Passer" },
  { id: "fringilla", family_id: "fringillidae", name_cn: "燕雀属", name_latin: "Fringilla" },
  { id: "carduelis", family_id: "fringillidae", name_cn: "金翅雀属", name_latin: "Carduelis" },
  { id: "parus", family_id: "paridae", name_cn: "山雀属", name_latin: "Parus" },
  { id: "cyanistes", family_id: "paridae", name_cn: "蓝山雀属", name_latin: "Cyanistes" },
  { id: "corvus", family_id: "corvidae", name_cn: "鸦属", name_latin: "Corvus" },
  { id: "pica", family_id: "corvidae", name_cn: "鹊属", name_latin: "Pica" },
  { id: "garrulus", family_id: "corvidae", name_cn: "松鸦属", name_latin: "Garrulus" },
  { id: "turdus", family_id: "turdidae", name_cn: "鸫属", name_latin: "Turdus" },
  { id: "erithacus", family_id: "muscicapidae", name_cn: "歌鸲属", name_latin: "Erithacus" },
  { id: "phoenicurus", family_id: "muscicapidae", name_cn: "红尾鸲属", name_latin: "Phoenicurus" },
  { id: "phylloscopus", family_id: "phylloscopidae", name_cn: "柳莺属", name_latin: "Phylloscopus" },
  { id: "garrulax", family_id: "timaliidae", name_cn: "噪鹛属", name_latin: "Garrulax" },
  { id: "pycnonotus", family_id: "pycnonotidae", name_cn: "鹎属", name_latin: "Pycnonotus" },
  { id: "dendrocopos", family_id: "picidae", name_cn: "啄木鸟属", name_latin: "Dendrocopos" },
  { id: "apus", family_id: "apodidae", name_cn: "雨燕属", name_latin: "Apus" },
  { id: "alcedo", family_id: "alcedinidae", name_cn: "翠鸟属", name_latin: "Alcedo" },
  { id: "cuculus", family_id: "cuculidae", name_cn: "杜鹃属", name_latin: "Cuculus" },
  { id: "otus", family_id: "strigidae", name_cn: "角鸮属", name_latin: "Otus" },
  { id: "bubo", family_id: "strigidae", name_cn: "雕鸮属", name_latin: "Bubo" },
  { id: "accipiter", family_id: "accipitridae", name_cn: "鹰属", name_latin: "Accipiter" },
  { id: "buteo", family_id: "accipitridae", name_cn: "鵟属", name_latin: "Buteo" },
  { id: "falco", family_id: "falconidae", name_cn: "隼属", name_latin: "Falco" },
  { id: "larus", family_id: "laridae", name_cn: "鸥属", name_latin: "Larus" },
  { id: "charadrius", family_id: "charadriidae", name_cn: "鸻属", name_latin: "Charadrius" },
  { id: "tringa", family_id: "scolopacidae", name_cn: "鹬属", name_latin: "Tringa" },
  { id: "grus", family_id: "gruidae", name_cn: "鹤属", name_latin: "Grus" },
  { id: "gallinula", family_id: "rallidae", name_cn: "黑水鸡属", name_latin: "Gallinula" },
  { id: "anas", family_id: "anatidae", name_cn: "鸭属", name_latin: "Anas" },
  { id: "anser", family_id: "anatidae", name_cn: "雁属", name_latin: "Anser" },
  { id: "phasianus", family_id: "phasianidae", name_cn: "雉属", name_latin: "Phasianus" },
  { id: "bambusicola", family_id: "phasianidae", name_cn: "竹鸡属", name_latin: "Bambusicola" },
  { id: "streptopelia", family_id: "columbidae", name_cn: "斑鸠属", name_latin: "Streptopelia" },
  { id: "columba", family_id: "columbidae", name_cn: "鸽属", name_latin: "Columba" },
];

const species: BirdSpecies[] = [
  {
    id: "sp_passer_montanus",
    genus_id: "passer",
    name_cn: "树麻雀",
    name_latin: "Passer montanus",
    common_name: "麻雀",
    habitat_type: "urban",
    residence_type: "resident",
    conservation_status: "LC",
    description:
      "体型略小(14厘米)的矮圆而活跃的麻雀。顶冠及颈背褐色，两性同色。成鸟上体近褐，下体皮黄灰色，颈背具完整的灰白色领环。",
    is_common: true,
  },
  {
    id: "sp_passer_domesticus",
    genus_id: "passer",
    name_cn: "家麻雀",
    name_latin: "Passer domesticus",
    habitat_type: "urban",
    residence_type: "resident",
    conservation_status: "LC",
    description:
      "中等体型(15厘米)的麻雀。雄鸟与树麻雀的区别在顶冠及尾上覆羽灰色，耳无黑色斑块，且喉及上胸的黑色较多。",
    is_common: true,
  },
  {
    id: "sp_fringilla_montifringilla",
    genus_id: "fringilla",
    name_cn: "燕雀",
    name_latin: "Fringilla montifringilla",
    habitat_type: "forest",
    residence_type: "winter_visitor",
    conservation_status: "LC",
    description:
      "中等体型(16厘米)而斑纹分明的壮实型雀鸟。胸橙而腰白。醒目而点斑密布的翼及黑色叉形的尾是其特征。",
    is_common: true,
  },
  {
    id: "sp_carduelis_sinica",
    genus_id: "carduelis",
    name_cn: "金翅雀",
    name_latin: "Carduelis sinica",
    common_name: "金翅",
    habitat_type: "farmland",
    residence_type: "resident",
    conservation_status: "LC",
    description:
      "体小(13厘米)的黄、灰及褐色雀鸟。具宽阔的黄色翼斑。成体雄鸟顶冠及颈背灰色，背纯褐色，翼斑、外侧尾羽基部及臀黄。",
    is_common: true,
  },
  {
    id: "sp_parus_major",
    genus_id: "parus",
    name_cn: "大山雀",
    name_latin: "Parus major",
    habitat_type: "forest",
    residence_type: "resident",
    conservation_status: "LC",
    description:
      "体大(14厘米)而结实的黑、灰及白色山雀。头及喉辉黑，与脸侧白斑及颈背块斑成强对比；翼上具一道醒目的白色条纹。",
    is_common: true,
  },
  {
    id: "sp_parus_ater",
    genus_id: "parus",
    name_cn: "煤山雀",
    name_latin: "Parus ater",
    habitat_type: "forest",
    residence_type: "resident",
    conservation_status: "LC",
    description:
      "体小(11厘米)的山雀。头顶、颈侧、喉及上胸黑色。翼上具两道白色翼斑以及颈背部的大块白斑使之有别于褐头山雀。",
    is_common: true,
  },
  {
    id: "sp_cyanistes_cyanus",
    genus_id: "cyanistes",
    name_cn: "蓝山雀",
    name_latin: "Cyanistes cyanus",
    habitat_type: "forest",
    residence_type: "resident",
    conservation_status: "LC",
    description: "体小(13厘米)的蓝白相间山雀。特征为头顶、冠羽及贯眼纹黑色，头侧白，上背蓝灰，下体偏白。",
    is_common: false,
  },
  {
    id: "sp_corvus_corax",
    genus_id: "corvus",
    name_cn: "渡鸦",
    name_latin: "Corvus corax",
    habitat_type: "mountain",
    residence_type: "resident",
    conservation_status: "LC",
    description: "体型甚大(66厘米)的全黑色鸦。与大嘴乌鸦区别在于体型较大，嘴形厚重，尾端呈楔形。",
    is_common: false,
  },
  {
    id: "sp_corvus_macrorhynchos",
    genus_id: "corvus",
    name_cn: "大嘴乌鸦",
    name_latin: "Corvus macrorhynchos",
    habitat_type: "urban",
    residence_type: "resident",
    conservation_status: "LC",
    description: "体大(50厘米)的闪光黑色鸦。嘴甚粗厚。比渡鸦体小而尾较平。",
    is_common: true,
  },
  {
    id: "sp_corvus_monedula",
    genus_id: "corvus",
    name_cn: "达乌里寒鸦",
    name_latin: "Corvus monedula",
    common_name: "寒鸦",
    habitat_type: "farmland",
    residence_type: "resident",
    conservation_status: "LC",
    description:
      "体型略小(32厘米)的鹊色鸦。白色斑纹延至胸下。与白颈鸦的区别在体型较小且嘴细，胸部白色部分较大。",
    is_common: true,
  },
  {
    id: "sp_pica_pica",
    genus_id: "pica",
    name_cn: "喜鹊",
    name_latin: "Pica pica",
    habitat_type: "urban",
    residence_type: "resident",
    conservation_status: "LC",
    description: "体型略小(45厘米)的鸦。特征为头、颈、背至尾均为黑色，并自前往后分别呈现紫色、绿蓝色、绿色等光泽。",
    is_common: true,
  },
  {
    id: "sp_garrulus_glandarius",
    genus_id: "garrulus",
    name_cn: "松鸦",
    name_latin: "Garrulus glandarius",
    habitat_type: "forest",
    residence_type: "resident",
    conservation_status: "LC",
    description:
      "体小(35厘米)的偏粉色鸦。特征为翼上具黑色及蓝色镶嵌图案，腰白。髭纹黑色，两翼黑色具白色块斑。",
    is_common: true,
  },
  {
    id: "sp_turdus_merula",
    genus_id: "turdus",
    name_cn: "乌鸫",
    name_latin: "Turdus merula",
    common_name: "百舌",
    habitat_type: "urban",
    residence_type: "resident",
    conservation_status: "LC",
    description: "体型略大(26厘米)的全深色鸫。雄鸟全黑色，嘴橘黄，眼圈略浅，脚黑。雌鸟上体黑褐，下体深褐，嘴暗绿黄色至黑色。",
    is_common: true,
  },
  {
    id: "sp_turdus_pallidus",
    genus_id: "turdus",
    name_cn: "灰背鸫",
    name_latin: "Turdus pallidus",
    habitat_type: "forest",
    residence_type: "passage_migrant",
    conservation_status: "LC",
    description: "体型略小(24厘米)的灰色鸫。两胁棕色。雄鸟上体全灰，喉灰或偏白，胸灰，腹中心及尾下覆羽白。",
    is_common: true,
  },
  {
    id: "sp_turdus_naumanni",
    genus_id: "turdus",
    name_cn: "斑鸫",
    name_latin: "Turdus naumanni",
    habitat_type: "farmland",
    residence_type: "winter_visitor",
    conservation_status: "LC",
    description:
      "中等体型(25厘米)而具明显黑白色图纹的鸫。具浅棕色的翼线和棕色的宽阔翼斑。雄鸟耳羽及胸上横纹黑色。",
    is_common: true,
  },
  {
    id: "sp_erithacus_akahige",
    genus_id: "erithacus",
    name_cn: "日本歌鸲",
    name_latin: "Erithacus akahige",
    habitat_type: "forest",
    residence_type: "passage_migrant",
    conservation_status: "LC",
    description:
      "体型小巧(15厘米)的歌鸲。上体褐色，脸及胸橘黄，两胁近灰。雄鸟具狭窄的黑色项纹环绕橘黄色胸围形斑。",
    is_common: false,
  },
  {
    id: "sp_phoenicurus_auroreus",
    genus_id: "phoenicurus",
    name_cn: "北红尾鸲",
    name_latin: "Phoenicurus auroreus",
    habitat_type: "urban",
    residence_type: "winter_visitor",
    conservation_status: "LC",
    description:
      "中等体型(15厘米)而色彩艳丽的红尾鸲。具明显而宽大的白色翼斑。雄鸟眼先、头侧、喉、上背及两翼褐黑，仅翼斑白色。",
    is_common: true,
  },
  {
    id: "sp_phylloscopus_inornatus",
    genus_id: "phylloscopus",
    name_cn: "黄腰柳莺",
    name_latin: "Phylloscopus inornatus",
    habitat_type: "forest",
    residence_type: "winter_visitor",
    conservation_status: "LC",
    description: "体小(9厘米)的背部橄榄色柳莺。特征为柠檬黄色的腰及淡色的短眉纹。两道偏黄白色的翼斑。",
    is_common: true,
  },
  {
    id: "sp_phylloscopus_proregulus",
    genus_id: "phylloscopus",
    name_cn: "黄眉柳莺",
    name_latin: "Phylloscopus proregulus",
    habitat_type: "forest",
    residence_type: "winter_visitor",
    conservation_status: "LC",
    description: "体小(10厘米)的柳莺。上体橄榄绿，眉纹黄色，贯眼纹深褐，头顶中央具一道不甚明显的淡黄绿色冠纹。",
    is_common: true,
  },
  {
    id: "sp_garrulax_canorus",
    genus_id: "garrulax",
    name_cn: "画眉",
    name_latin: "Garrulax canorus",
    habitat_type: "forest",
    residence_type: "resident",
    conservation_status: "LC",
    description:
      "体型略小(22厘米)的棕褐色鹛。特征为白色的眼圈在眼后延伸成狭窄的眉纹。顶冠及颈背有偏黑色纵纹。",
    is_common: true,
  },
  {
    id: "sp_pycnonotus_sinensis",
    genus_id: "pycnonotus",
    name_cn: "白头鹎",
    name_latin: "Pycnonotus sinensis",
    common_name: "白头翁",
    habitat_type: "urban",
    residence_type: "resident",
    conservation_status: "LC",
    description:
      "中等体型(19厘米)的橄榄色鹎。眼后一白色宽纹伸至颈背，黑色的头顶略具羽冠，髭纹黑色，臀白。",
    is_common: true,
  },
  {
    id: "sp_pycnonotus_jocosus",
    genus_id: "pycnonotus",
    name_cn: "红耳鹎",
    name_latin: "Pycnonotus jocosus",
    habitat_type: "urban",
    residence_type: "resident",
    conservation_status: "LC",
    description:
      "中等体型(20厘米)的鹎。黑色的羽冠长窄而前倾，特征为黑白色的头部图纹上具红色耳斑。上体余部偏褐色，下体皮黄，臀红，尾端具白色缘。",
    is_common: true,
  },
  {
    id: "sp_dendrocopos_major",
    genus_id: "dendrocopos",
    name_cn: "大斑啄木鸟",
    name_latin: "Dendrocopos major",
    habitat_type: "forest",
    residence_type: "resident",
    conservation_status: "LC",
    description:
      "体型中等(24厘米)的常见型黑相间的啄木鸟。雄鸟枕部具狭窄红色带而雌鸟无。两性臀部均为红色，但带黑色纵纹的近白色胸部上无红色。",
    is_common: true,
  },
  {
    id: "sp_dendrocopos_canicapillus",
    genus_id: "dendrocopos",
    name_cn: "灰头绿啄木鸟",
    name_latin: "Picus canus",
    habitat_type: "forest",
    residence_type: "resident",
    conservation_status: "LC",
    description:
      "中等体型(27厘米)的绿色啄木鸟。雄鸟前顶冠猩红，眼先及狭窄颊纹黑色。枕及尾黑色。雌鸟顶冠灰色而无红斑。",
    is_common: true,
  },
  {
    id: "sp_apus_apus",
    genus_id: "apus",
    name_cn: "普通雨燕",
    name_latin: "Apus apus",
    common_name: "楼燕",
    habitat_type: "urban",
    residence_type: "summer_visitor",
    conservation_status: "LC",
    description: "中等体型(17厘米)的雨燕尾略叉开，特征为白色的喉及胸部为一道深褐色的横带所隔开。两翼相当宽。",
    is_common: true,
  },
  {
    id: "sp_apus_pacificus",
    genus_id: "apus",
    name_cn: "白腰雨燕",
    name_latin: "Apus pacificus",
    habitat_type: "coastal",
    residence_type: "summer_visitor",
    conservation_status: "LC",
    description: "体型略大(18厘米)的污褐色雨燕。尾长而尾叉深，颏偏白，腰上有白斑。",
    is_common: true,
  },
  {
    id: "sp_alcedo_atthis",
    genus_id: "alcedo",
    name_cn: "普通翠鸟",
    name_latin: "Alcedo atthis",
    habitat_type: "wetland",
    residence_type: "resident",
    conservation_status: "LC",
    description:
      "体小(15厘米)、具亮蓝色及棕色的翠鸟。上体金属浅蓝绿色，颈侧具白色点斑；下体橙棕色，颏白。",
    is_common: true,
  },
  {
    id: "sp_cuculus_canorus",
    genus_id: "cuculus",
    name_cn: "大杜鹃",
    name_latin: "Cuculus canorus",
    common_name: "布谷鸟",
    habitat_type: "forest",
    residence_type: "summer_visitor",
    conservation_status: "LC",
    description:
      "中等体型(32厘米)的杜鹃。上体灰色，尾偏黑色，腹部近白而具黑色横斑。'棕红色'变异型雌鸟为棕色，背部具黑色横斑。",
    is_common: true,
  },
  {
    id: "sp_cuculus_micropterus",
    genus_id: "cuculus",
    name_cn: "四声杜鹃",
    name_latin: "Cuculus micropterus",
    habitat_type: "forest",
    residence_type: "summer_visitor",
    conservation_status: "LC",
    description: "中等体型(30厘米)的杜鹃。头顶及颈背灰色，背褐，尾黑而端白，下体皮黄而具黑色粗纹。",
    is_common: true,
  },
  {
    id: "sp_otus_scops",
    genus_id: "otus",
    name_cn: "红角鸮",
    name_latin: "Otus scops",
    habitat_type: "forest",
    residence_type: "summer_visitor",
    conservation_status: "LC",
    description: "体小(19厘米)而褐色斑驳的角鸮。眼黄色，胸满布黑色条纹。",
    is_common: false,
  },
  {
    id: "sp_bubo_bubo",
    genus_id: "bubo",
    name_cn: "雕鸮",
    name_latin: "Bubo bubo",
    habitat_type: "mountain",
    residence_type: "resident",
    conservation_status: "NT",
    description: "体型硕大(69厘米)的鸮类。体羽褐色斑驳。胸部片黄，多具深褐色纵纹且每片羽毛均具褐色横斑。",
    is_common: false,
  },
  {
    id: "sp_accipiter_nisus",
    genus_id: "accipiter",
    name_cn: "雀鹰",
    name_latin: "Accipiter nisus",
    habitat_type: "forest",
    residence_type: "resident",
    conservation_status: "LC",
    description: "中等体型(雄鸟32厘米，雌鸟38厘米)而翼短的鹰。雄鸟上体灰色，腹部棕色横斑浓密。雌鸟体型较大，上体褐灰，下体较少棕色。",
    is_common: true,
  },
  {
    id: "sp_accipiter_gentilis",
    genus_id: "accipiter",
    name_cn: "苍鹰",
    name_latin: "Accipiter gentilis",
    habitat_type: "forest",
    residence_type: "resident",
    conservation_status: "LC",
    description: "体大(56厘米)而强健的鹰。无冠羽或喉中线，具白色的宽眉纹。成鸟下体白色上具粉褐色横斑，上体青灰。",
    is_common: false,
  },
  {
    id: "sp_buteo_buteo",
    genus_id: "buteo",
    name_cn: "普通鵟",
    name_latin: "Buteo buteo",
    habitat_type: "farmland",
    residence_type: "winter_visitor",
    conservation_status: "LC",
    description:
      "中等体型(55厘米)的红褐色鵟。上体深红褐色，脸侧皮黄具近红色细纹，下体偏白而具深色纵纹，腹部有深褐色横斑。",
    is_common: true,
  },
  {
    id: "sp_falco_tinnunculus",
    genus_id: "falco",
    name_cn: "红隼",
    name_latin: "Falco tinnunculus",
    habitat_type: "farmland",
    residence_type: "resident",
    conservation_status: "LC",
    description: "体小(33厘米)的赤褐色隼。雄鸟头顶及颈背灰色，尾蓝灰无横斑，上体赤褐略具黑色横斑，下体皮黄而具黑色纵纹。",
    is_common: true,
  },
  {
    id: "sp_falco_peregrinus",
    genus_id: "falco",
    name_cn: "游隼",
    name_latin: "Falco peregrinus",
    habitat_type: "coastal",
    residence_type: "resident",
    conservation_status: "LC",
    description: "体大(45厘米)而强壮的深色隼。成鸟头顶及脸颊近黑或具黑色条纹；上体深灰具黑色点斑及横纹；下体白，胸具黑色纵纹。",
    is_common: false,
  },
  {
    id: "sp_larus_ridibundus",
    genus_id: "larus",
    name_cn: "红嘴鸥",
    name_latin: "Chroicocephalus ridibundus",
    habitat_type: "wetland",
    residence_type: "winter_visitor",
    conservation_status: "LC",
    description: "中等体型(40厘米)的灰色、白色及深褐色鸥。繁殖羽：头及颈深咖啡色，至冬季转为纯白色。",
    is_common: true,
  },
  {
    id: "sp_charadrius_dubius",
    genus_id: "charadrius",
    name_cn: "环颈鸻",
    name_latin: "Charadrius dubius",
    habitat_type: "wetland",
    residence_type: "summer_visitor",
    conservation_status: "LC",
    description:
      "体小(15厘米)而嘴短的褐色及白色鸻。与金眶鸻的区别在腿黑色，飞行时具白色翼上横纹，尾羽外侧更白。",
    is_common: true,
  },
  {
    id: "sp_tringa_ochropus",
    genus_id: "tringa",
    name_cn: "白腰草鹬",
    name_latin: "Tringa ochropus",
    habitat_type: "wetland",
    residence_type: "winter_visitor",
    conservation_status: "LC",
    description:
      "中等体型(23厘米)，矮壮型，深绿褐色，腹部及臀白色。飞行时黑色的下翼、白色的腰部以及尾部的横斑极显著。",
    is_common: true,
  },
  {
    id: "sp_grus_grus",
    genus_id: "grus",
    name_cn: "灰鹤",
    name_latin: "Grus grus",
    habitat_type: "wetland",
    residence_type: "winter_visitor",
    conservation_status: "NT",
    description: "体型中等(125厘米)的灰色鹤。前顶冠黑色，中心红色，头及颈深青灰色。自眼后有一道宽的白色条纹伸至颈背。",
    is_common: false,
  },
  {
    id: "sp_gallinula_chloropus",
    genus_id: "gallinula",
    name_cn: "黑水鸡",
    name_latin: "Gallinula chloropus",
    habitat_type: "wetland",
    residence_type: "resident",
    conservation_status: "LC",
    description: "中等体型(31厘米)，黑白色，额甲亮红，嘴短。体羽全青黑色，仅两胁有白色细纹而成的线条以及尾下有两块白斑。",
    is_common: true,
  },
  {
    id: "sp_anas_platyrhynchos",
    genus_id: "anas",
    name_cn: "绿头鸭",
    name_latin: "Anas platyrhynchos",
    habitat_type: "wetland",
    residence_type: "winter_visitor",
    conservation_status: "LC",
    description:
      "中等体型(58厘米)，为家鸭的野型。雄鸟头及颈深绿色带光泽，白色颈环使头与栗色胸隔开。雌鸟褐色斑驳，有深色的贯眼纹。",
    is_common: true,
  },
  {
    id: "sp_anas_poecilorhyncha",
    genus_id: "anas",
    name_cn: "斑嘴鸭",
    name_latin: "Anas poecilorhyncha",
    habitat_type: "wetland",
    residence_type: "resident",
    conservation_status: "LC",
    description: "体大(60厘米)的深褐色鸭。头色浅，顶及眼线色深，嘴黑而嘴端黄且于繁殖期黄色嘴端顶尖有一黑点为本种特征。",
    is_common: true,
  },
  {
    id: "sp_anser_anser",
    genus_id: "anser",
    name_cn: "灰雁",
    name_latin: "Anser anser",
    habitat_type: "wetland",
    residence_type: "winter_visitor",
    conservation_status: "LC",
    description: "体大(76厘米)的灰褐色雁。以粉红色的嘴和脚为本种特征。嘴基无白色。上体体羽灰而羽缘白，使上体具扇贝形图纹。",
    is_common: false,
  },
  {
    id: "sp_phasianus_colchicus",
    genus_id: "phasianus",
    name_cn: "环颈雉",
    name_latin: "Phasianus colchicus",
    common_name: "雉鸡",
    habitat_type: "farmland",
    residence_type: "resident",
    conservation_status: "LC",
    description:
      "雄鸟：体大(85厘米)、头部具黑色光泽，有显眼的耳羽簇，宽大的眼周裸皮鲜红色。雌鸟：形小(60厘米)，为暗淡的斑驳褐色。",
    is_common: true,
  },
  {
    id: "sp_bambusicola_thoracicus",
    genus_id: "bambusicola",
    name_cn: "灰胸竹鸡",
    name_latin: "Bambusicola thoracicus",
    habitat_type: "forest",
    residence_type: "resident",
    conservation_status: "LC",
    description: "中等体型(33厘米)的红棕色鹑类。特征为额、眉线及颈项蓝灰色，与脸、喉及上胸的棕色成对比。",
    is_common: true,
  },
  {
    id: "sp_streptopelia_decaocto",
    genus_id: "streptopelia",
    name_cn: "灰斑鸠",
    name_latin: "Streptopelia decaocto",
    habitat_type: "urban",
    residence_type: "resident",
    conservation_status: "LC",
    description: "中等体型(32厘米)的褐灰色斑鸠。明显特征为后颈具黑白色半领圈。较山斑鸠以及体小得多的粉色火斑鸠更显浅灰色。",
    is_common: true,
  },
  {
    id: "sp_streptopelia_orientalis",
    genus_id: "streptopelia",
    name_cn: "山斑鸠",
    name_latin: "Streptopelia orientalis",
    habitat_type: "farmland",
    residence_type: "resident",
    conservation_status: "LC",
    description: "中等体型(32厘米)的偏粉色斑鸠。与珠颈斑鸠区别在于颈侧有带明显黑白色条纹的块状斑。",
    is_common: true,
  },
  {
    id: "sp_spilopelia_chinensis",
    genus_id: "streptopelia",
    name_cn: "珠颈斑鸠",
    name_latin: "Spilopelia chinensis",
    habitat_type: "urban",
    residence_type: "resident",
    conservation_status: "LC",
    description: "中等体型(30厘米)的粉褐色斑鸠。尾略显长，外侧尾羽前端的白色甚宽，飞羽较体羽色深。明显特征为颈侧满是白点的黑色块斑。",
    is_common: true,
  },
  {
    id: "sp_columba_livia",
    genus_id: "columba",
    name_cn: "原鸽",
    name_latin: "Columba livia",
    common_name: "岩鸽",
    habitat_type: "urban",
    residence_type: "resident",
    conservation_status: "LC",
    description: "中等体型(32厘米)的蓝灰色鸽。翼上横斑及尾端横斑黑色，头及胸部具紫绿色闪光。",
    is_common: true,
  },
];

export async function seedBirdData(db: BirdingDB): Promise<void> {
  const tx = db.transaction(
    ["bird_orders", "bird_families", "bird_genera", "bird_species"],
    "readwrite"
  );

  for (const o of orders) {
    await tx.objectStore("bird_orders").put(o);
  }
  for (const f of families) {
    await tx.objectStore("bird_families").put(f);
  }
  for (const g of genera) {
    await tx.objectStore("bird_genera").put(g);
  }
  for (const s of species) {
    await tx.objectStore("bird_species").put(s);
  }

  await tx.done;
}
